# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: "C:\\windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" -NoLogo -NoProfile -Interactive -ExecutionPolicy Unrestricted -Command ". 'D:\\a\\_temp\\e00394f7-1b1a-45a8-8588-c0cf774b8311.ps1'"
  displayName: 'Run a one-line script'

- powershell: .\PowerBiProUser.ps1
  displayName: 'Run a powershell script'
